import Posts from "components/Posts";
import { getPosts } from "lib/data";
import prisma from "lib/prisma";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home({ posts }) {
  const { data: session, status } = useSession();
  const router = useRouter();
  const loading = status === 'loading';

  if (loading) {
    return null;
  }

  if (session && !session.user.name) {
    router.push('/setup');
  }

  return (
    <div>
      <Head>
        <title>Reddit Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      
      <header className='bg-black text-white font-bold h-12 flex pt-3 px-20 pb-2'>
        <p className="text-bold">Reddit Clone</p>
        <p className="grow"></p>
        <a
          className='flex-l border px-4 pb-6 font-bold rounded-full mb-1' 
          href={session ? "/api/auth/signout" : "/api/auth/signin"}
        >
          {session ? 'logout' : 'login'}
        </a>
      </header>
      {session && (
        <pre>
          { JSON.stringify(session, null, 2) }
        </pre>
      )}
      <Posts posts={posts} />
    </div>
  );
}

export async function getServerSideProps() {
  let posts = await getPosts(prisma);
  posts = JSON.parse(JSON.stringify(posts));

  return {
    props: {
      posts
    }
  }
}